apiVersion: apps/v1
kind: Deployment
metadata:
  name: mota-1st-deploy
  labels:
    app: mota_build-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mota-lbl
  template:
    metadata:
      labels:
        app: mota-lbl
    spec:
      containers:
      - name: mota-container
        image: prashant6395/mota-webapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mota-np-service
  labels:
    app: mota-lbl
spec:
  selector:
    app: mota-lbl

  type: NodePort
  ports:
  - nodePort: 30020
    port: 8080
    targetPort: 8080
