# =============================
# DEPLOYMENT
# =============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-deployment          # Change this - your deployment name
  labels:
    app: banking-app                # Change this - your app label
spec:
  replicas: 3                  # Change this - number of pods
  selector:
    matchLabels:
      app: banking-app              # Must match labels.app above
  template:
    metadata:
      labels:
        app: banking-app           # Must match selector.matchLabels.app above
    spec:
      containers:
      - name: learning-container     # Change this - your container name
        image: prashant6395/bankapp-image:v3.0  # Change this - e.g. nginx:latest or tomcat:9.0
        ports:
        - containerPort: 8080  # Change this - port your app runs on inside container
 
---
# =============================
# NODEPORT SERVICE
# =============================
apiVersion: v1
kind: Service
metadata:
  name: learning-deployment-svc    # Change this - your service name
spec:
  type: NodePort
  selector:
    app: banking-app                # Must match deployment labels.app above
  ports:
  - port: 80                   # ClusterIP port (internal)
    targetPort: 8080           # Must match containerPort above
